### PR TITLE
Rethrow the error caught when builder fails

### LINKED ISSUE #237: Need more informative error
https://github.com/FluxML/MLJFlux.jl/blob/4fa632de257cfde9dc0b01693b1f4270a4ecc405/src/mlj_model_interface.jl#L61

Throw-catch block here needs to throw the caught exception after the `@error`. At present users are hitting some uninformative errors. 

@OkonSamuel

### PR DESCRIPTION
**Pull request by ablaom**
Closes #237

There is presently a `throw`-`catch` block to check a user-provided builder will successfully create a Flux model. This PR ensures that the exception causing the fail is ultimately thrown.

### CODE REVIEW

**Comment by ablaom** [comment]
@OkonSamuel Could you please review this? I've sent you an contributor invitation.

File: src/mlj_model_interface.jl [hunk 1]
```diff
@@ -59,6 +59,7 @@ function MLJModelInterface.fit(model::MLJFluxModel,
         build(model, rng, shape) |> move
     catch ex
         @error ERR_BUILDER
+        throw(ex)
```
Comment (OkonSamuel) [inline src/mlj_model_interface.jl:62]:
```suggestion
        rethrow()
```
Lets use rethrow here as its more cleaner

**Review by OkonSamuel — CHANGES_REQUESTED** [review]

**Comment by ablaom** [comment]
I've added a test.

**Comment by ablaom** [comment]
I think we can ignore the nightly fail.

@OkonSamuel Are you happy for a merge?

**Review by OkonSamuel — APPROVED** [review]
